#Setea el directorio de trabajo
setwd("/temp/VP")
#Lee conjunto de datos
Vs<-read.delim("Vs.txt", header = FALSE, sep = " ", dec = ".")
Tr<-read.delim("Tr.txt", header = FALSE, sep = " ", dec = ".")
V1<-read.delim("V1.txt", header = FALSE, sep = " ", dec = ".")
V2<-read.delim("V2.txt", header = FALSE, sep = " ", dec = ".")
T1<-read.delim("T1.txt", header = FALSE, sep = " ", dec = ".")
T2<-read.delim("T2.txt", header = FALSE, sep = " ", dec = ".")
#Crea vectores para Y negativas
neg_Vs<-vector(mode='numeric', length=nrow(Vs))
neg_Tr<-vector(mode='numeric', length=nrow(Tr))
neg_V1<-vector(mode='numeric', length=nrow(V1))
neg_V2<-vector(mode='numeric', length=nrow(V2))
neg_T1<-vector(mode='numeric', length=nrow(T1))
neg_T2<-vector(mode='numeric', length=nrow(T2))
#Coloca nueva columna en Data respectiva
Vs<-data.frame(Vs, neg_Vs)
Tr<-data.frame(Tr, neg_Tr)
V1<-data.frame(V1, neg_V1)
V2<-data.frame(V2, neg_V2)
T1<-data.frame(T1, neg_T1)
T2<-data.frame(T2, neg_T2)
#Renombra columnas
colnames(Vs)= c('x','y','ny')
colnames(Tr)= c('x','y','ny')
colnames(V1)= c('x','y','ny')
colnames(V2)= c('x','y','ny')
colnames(T1)= c('x','y','ny')
colnames(T2)= c('x','y','ny')
#Calcula Y negativas para graficar invertido el eje Y
Vs$ny<-Vs$y*(-1)
Tr$ny<-Tr$y*(-1)
V1$ny<-V1$y*(-1)
V2$ny<-V2$y*(-1)
T1$ny<-T1$y*(-1)
T2$ny<-T2$y*(-1)
#Carga libreria para mapas de calor y calcula
require(MASS)
hp_Vs <- kde2d(Vs$x, Vs$ny, h=75, n=50)
hp_Tr <- kde2d(Tr$x, Tr$ny, h=75, n=50)
hp_V1 <- kde2d(V1$x, V1$ny, h=75, n=50)
hp_V2 <- kde2d(V2$x, V2$ny, h=75, n=50)
hp_T1 <- kde2d(T1$x, T1$ny, h=75, n=50)
hp_T2 <- kde2d(T2$x, T2$ny, h=75, n=50)
#Cambia paleta de colores
pcolores <- colorRampPalette(c("#00007F", "blue", "#007FFF", "cyan", "#7FFF7F", "yellow", "#FF7F00", "red", "#7F0000"))
#Grafica mapas de calor
par(mfrow = c(2, 1))
filled.contour(hp_Vs, color = pcolores, asp = 1, xlab = "X", ylab = "Y", main = "Visual")
filled.contour(hp_Tr, color = pcolores, asp = 1, xlab = "X", ylab = "Y", main = "Tradicional")
par(mfrow = c(2, 2))
filled.contour(hp_V1, color = pcolores, asp = 1, xlab = "X", ylab = "Y", main = "V1")
filled.contour(hp_V2, color = pcolores, asp = 1, xlab = "X", ylab = "Y", main = "V2")
filled.contour(hp_T1, color = pcolores, asp = 1, xlab = "X", ylab = "Y", main = "T1")
filled.contour(hp_T2, color = pcolores, asp = 1, xlab = "X", ylab = "Y", main = "T2")